name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "25.2"
          gleam-version: "1.1.0"
          rebar3-version: "3"
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: gleam format --check src test
      - run: gleam deps download

      - run: gleam test --target erlang
      - run: gleam test --target javascript
